"""Seeds the database with initial data from supabase-schema-corrigido.sql."""

import json
import asyncio

from sqlalchemy import text
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine

from app.core.config import settings


PERGUNTAS_OPCOES = [
    {
        "id": "I01",
        "categoria": "Disponibilidade",
        "pergunta": "Em relação aos dados necessários para desempenhar minhas atividades, tenho acesso a:",
        "tipo": "radio",
        "opcoes": [{"valor": 0, "texto": "Parte deles"}, {"valor": 1, "texto": "Todos"}],
        "ordem": 1,
    },
    {
        "id": "I02",
        "categoria": "Disponibilidade",
        "pergunta": "Os dados que tenho acesso são consistentes, corretos e atendem às expectativas.",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Discordo totalmente"},
            {"valor": 1, "texto": "Discordo"},
            {"valor": 2, "texto": "Concordo"},
            {"valor": 3, "texto": "Concordo totalmente"},
        ],
        "ordem": 2,
    },
    {
        "id": "I03",
        "categoria": "Disponibilidade",
        "pergunta": "Os dados são atualizados e disponibilizados em tempo adequado para realizar o meu trabalho.",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Discordo totalmente"},
            {"valor": 1, "texto": "Discordo"},
            {"valor": 2, "texto": "Concordo"},
            {"valor": 3, "texto": "Concordo totalmente"},
        ],
        "ordem": 3,
    },
    {
        "id": "I04",
        "categoria": "Disponibilidade",
        "pergunta": "As ferramentas de análise de dados fornecidas pela empresa são adequadas para as análises que preciso realizar.",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Discordo totalmente"},
            {"valor": 1, "texto": "Discordo"},
            {"valor": 2, "texto": "Concordo"},
            {"valor": 3, "texto": "Concordo totalmente"},
        ],
        "ordem": 4,
    },
    {
        "id": "I05",
        "categoria": "Disponibilidade",
        "pergunta": "As ferramentas de dados disponibilizadas pela empresa são fáceis de serem utilizadas.",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Discordo totalmente"},
            {"valor": 1, "texto": "Discordo"},
            {"valor": 2, "texto": "Concordo"},
            {"valor": 3, "texto": "Concordo totalmente"},
        ],
        "ordem": 5,
    },
    {
        "id": "I06",
        "categoria": "Disponibilidade",
        "pergunta": "Quando temos problemas técnicos, o suporte técnico de dados e ferramentas é:",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Ineficaz"},
            {"valor": 1, "texto": "Pouco eficaz"},
            {"valor": 2, "texto": "Eficaz"},
            {"valor": 3, "texto": "Muito eficaz"},
        ],
        "ordem": 6,
    },
    {
        "id": "I07",
        "categoria": "Disponibilidade",
        "pergunta": "Posso contar com profissionais especializados para auxiliar, estruturar ou gerar os dados e análises necessários para o meu trabalho.",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Nunca"},
            {"valor": 1, "texto": "Poucas vezes"},
            {"valor": 2, "texto": "Na maioria das vezes"},
            {"valor": 3, "texto": "Sempre"},
        ],
        "ordem": 7,
    },
    {
        "id": "I08",
        "categoria": "Disponibilidade",
        "pergunta": "A documentação de como os dados são definidos, coletados e tratados facilita minha compreensão das métricas da empresa.",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Discordo totalmente"},
            {"valor": 1, "texto": "Discordo"},
            {"valor": 2, "texto": "Concordo"},
            {"valor": 3, "texto": "Concordo totalmente"},
        ],
        "ordem": 8,
    },
    {
        "id": "I09",
        "categoria": "Incentivo ao desenvolvimento",
        "pergunta": "Os treinamentos oferecidos pela empresa colaboram para que eu use mais os dados no meu dia a dia.",
        "tipo": "simNao",
        "opcoes": [{"valor": 0, "texto": "Não"}, {"valor": 1, "texto": "Sim"}],
        "ordem": 9,
    },
    {
        "id": "I10",
        "categoria": "Incentivo ao desenvolvimento",
        "pergunta": "A empresa incentiva o desenvolvimento de competências para gerar informações a partir dos dados.",
        "tipo": "simNao",
        "opcoes": [{"valor": 0, "texto": "Não"}, {"valor": 1, "texto": "Sim"}],
        "ordem": 10,
    },
    {
        "id": "I11",
        "categoria": "Incentivo ao desenvolvimento",
        "pergunta": "A empresa incentiva o desenvolvimento de técnicas de comunicação para apresentar análises, insights e informações obtidas pelos dados.",
        "tipo": "simNao",
        "opcoes": [{"valor": 0, "texto": "Não"}, {"valor": 1, "texto": "Sim"}],
        "ordem": 11,
    },
    {
        "id": "I12",
        "categoria": "Incentivo ao desenvolvimento",
        "pergunta": "A empresa incentiva a realização de testes para verificar hipóteses de negócios.",
        "tipo": "simNao",
        "opcoes": [{"valor": 0, "texto": "Não"}, {"valor": 1, "texto": "Sim"}],
        "ordem": 12,
    },
    {
        "id": "I13",
        "categoria": "Suporte da liderança",
        "pergunta": "Os líderes investem em profissionais qualificados para a realização das análises com base em dados.",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Nunca"},
            {"valor": 1, "texto": "Nem sempre"},
            {"valor": 2, "texto": "Sempre"},
        ],
        "ordem": 13,
    },
    {
        "id": "I14",
        "categoria": "Suporte da liderança",
        "pergunta": "Sei quais são os objetivos da empresa para o uso de dados.",
        "tipo": "simNao",
        "opcoes": [{"valor": 0, "texto": "Não"}, {"valor": 1, "texto": "Sim"}],
        "ordem": 14,
    },
    {
        "id": "I15",
        "categoria": "Benefícios individuais",
        "pergunta": "Tomo ações melhores e mais rápidas com o uso de dados da empresa.",
        "tipo": "simNao",
        "opcoes": [{"valor": 0, "texto": "Não"}, {"valor": 1, "texto": "Sim"}],
        "ordem": 15,
    },
    {
        "id": "I16",
        "categoria": "Benefícios individuais",
        "pergunta": "As informações geradas pelos dados têm resultado aplicável aos processos da empresa.",
        "tipo": "simNao",
        "opcoes": [{"valor": 0, "texto": "Não"}, {"valor": 1, "texto": "Sim"}],
        "ordem": 16,
    },
    {
        "id": "I17",
        "categoria": "Resultados para a empresa",
        "pergunta": "Meus líderes utilizam as informações geradas a partir dos dados para tomar decisões.",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Nunca"},
            {"valor": 1, "texto": "Nem sempre"},
            {"valor": 2, "texto": "Sempre"},
        ],
        "ordem": 17,
    },
    {
        "id": "I18",
        "categoria": "Resultados para a empresa",
        "pergunta": "Os líderes investem em profissionais qualificados para a realização das análises com base em dados.",
        "tipo": "escala",
        "opcoes": [
            {"valor": 0, "texto": "Nunca"},
            {"valor": 1, "texto": "Nem sempre"},
            {"valor": 2, "texto": "Sempre"},
        ],
        "ordem": 18,
    },
]

PERGUNTAS_PREFERENCIAS = [
    {
        "id": "P01",
        "categoria": "Preferencias",
        "pergunta": "Os colaboradores devem ser capacitados para utilizar as ferramentas de forma eficiente, desenvolvendo habilidades que vao alem do aspecto tecnico e incluam a aplicacao pratica para resolver problemas reais do negocio.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 1,
    },
    {
        "id": "P02",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que a organizacao invista em educacao e treinamentos focados no desenvolvimento de competencias em analise de informacoes e gestao de dados.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 2,
    },
    {
        "id": "P03",
        "categoria": "Preferencias",
        "pergunta": "E essencial que haja uma integracao entre evidencias derivada dos dados e o conhecimento humano, utilizando a experimentacao frequente como metodo para otimizar decisoes e superar escolhas baseadas apenas em experiencias passadas.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 3,
    },
    {
        "id": "P04",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que a organizacao promova workshops envolvendo diferentes equipes e espacos de demonstracao onde melhores praticas sejam compartilhadas, fornecendo reforco positivo e exemplos concretos de como as informacoes sao utilizadas na pratica",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 4,
    },
    {
        "id": "P05",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que os colaboradores percebam como as ferramentas de analise podem gerar valor para o negocio e desenvolvam uma atitude proativa no uso das informacoes disponiveis.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 5,
    },
    {
        "id": "P06",
        "categoria": "Preferencias",
        "pergunta": "Os colaboradores devem ser capazes de realizar suas tarefas com qualidade de forma independente, equilibrando atividades rotineiras e de inovacao, e utilizem sua experiencia pratica para validar a consistencia das informacoes.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 6,
    },
    {
        "id": "P07",
        "categoria": "Preferencias",
        "pergunta": "E essencial que os colaboradores desenvolvam a habilidade de coletar, analisar, interpretar e comunicar informacoes de forma eficiente, aplicando metodos analiticos para descrever o uso e o valor das informacoes disponiveis.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 7,
    },
    {
        "id": "P08",
        "categoria": "Preferencias",
        "pergunta": "A organizacao deve reconhecer e superar a distribuicao desigual de competencias em analise de dados, pois a baixa utilizacao ocorre quando os colaboradores nao tem consciencia das possibilidades que as informacoes oferecem ou nao sabem como visualizar e gerar valor a partir delas.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 8,
    },
    {
        "id": "P09",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que os lideres comuniquem claramente a visao de mudanca desejada e demonstrem no dia a dia como utilizar dados para tomar decisoes, influenciando assim toda a estrutura organizacional.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 9,
    },
    {
        "id": "P10",
        "categoria": "Preferencias",
        "pergunta": "A gestao deve promover a mudanca de mentalidade dos proprios gestores, incentivando-os a questionar suas suposicoes e a substituir decisoes baseadas apenas em intuicao por analises fundamentadas em evidencias concretas.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 10,
    },
    {
        "id": "P11",
        "categoria": "Preferencias",
        "pergunta": "A empresa deve criar um cargo de alta gestao especifico para os dados para atuar como facilitador da transformacao e operacionalizar a cultura desejada.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 11,
    },
    {
        "id": "P12",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que independentemente do nivel hierarquico e do conhecimento em analise de dados, todos os colaboradores sejam incentivados trocar experiencias com especialistas e a propor insights baseados em dados.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 12,
    },
    {
        "id": "P13",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que os colaboradores explorem, compartilhem e apliquem ativamente o conhecimento disponivel, colaborando para usar o conhecimento na organizacao para criar vantagens estrategicas diante das mudancas constantes.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 13,
    },
    {
        "id": "P14",
        "categoria": "Preferencias",
        "pergunta": "E fundamental desenvolver a capacidade analitica, seja ela descritiva, preditiva ou prescritiva, permitindo analisar informacoes em tempo real de diversas fontes.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 14,
    },
    {
        "id": "P15",
        "categoria": "Preferencias",
        "pergunta": "A organizacao deve estar disposta mudar os arranjos de poder dentro da organizacao, definindo responsabilidades individuais para implementacao de analises e sendo tolerante ao teste e erro.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 15,
    },
    {
        "id": "P16",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que a organizacao defina e institua papeis especializados, como analistas de dados, cientista de dados e gestor de dados, pois a institucionalizacao de cargos atua como propagador das funcoes desejadas na organizacao.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 16,
    },
    {
        "id": "P17",
        "categoria": "Preferencias",
        "pergunta": "Os lideres devem estabelecer principios comuns sobre o uso de informacoes e garantir que pressoes comerciais nao comprometam a qualidade das decisoes baseadas em fatos e dados.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 17,
    },
    {
        "id": "P18",
        "categoria": "Preferencias",
        "pergunta": "A organizacao deve disponibilizar sistemas que permitam acessar e utilizar os dados de forma autonoma e agil, com relatorios automatizados e uma operacao eficiente entre as equipes de negocio e tecnologia da informacao.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 18,
    },
    {
        "id": "P19",
        "categoria": "Preferencias",
        "pergunta": "A organizacao deve garantir transparencia sobre a origem e o uso das informacoes, fornecendo dados de alta qualidade e consistencia para que os colaboradores desenvolvam confianca e senso de responsabilidade.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 19,
    },
    {
        "id": "P20",
        "categoria": "Preferencias",
        "pergunta": "A organizacao deve estabelecer regras claras para maximizar o valor extraido das informacoes enquanto minimiza riscos e custos, garantindo a coleta correta dos dados e definindo uma fonte unica e confiavel de informacoes.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 20,
    },
    {
        "id": "P21",
        "categoria": "Preferencias",
        "pergunta": "E essencial que a empresa defina claramente quem e responsavel pela captura, veracidade e governanca das informacoes, e institucionalize principios eticos de transparencia, privacidade e controle rigoroso de acesso a dados sensiveis.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 21,
    },
    {
        "id": "P22",
        "categoria": "Preferencias",
        "pergunta": "Um setor especializado deve estabelecer a visao, estrategia e governanca para todas as iniciativas de dados, garantindo o bom funcionamento dos sistemas, o uso etico e responsavel das informacoes, e responsabilizando-se pelas decisoes sobre manutencao e evolucao dos mecanismos de governanca.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 22,
    },
    {
        "id": "P23",
        "categoria": "Preferencias",
        "pergunta": "Os membros da organizacao devem compartilhar informacoes e conhecimentos, colaborar e comunicar uns com os outros para que a aprendizagem continua dos membros possa mitigar divergencias e reduzir conflitos.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 23,
    },
    {
        "id": "P24",
        "categoria": "Preferencias",
        "pergunta": "Os membros da organizacao necessitam desenvolver habilidades de comunicacao, capacitando-se para compartilhar informacoes eficazmente e traduzir analises tecnicas em informacoes praticas que orientem decisoes de negocio.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 24,
    },
    {
        "id": "P25",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que a organizacao documente e comunique uma visao clara sobre o uso de dados, alinhada as necessidades do negocio seja aplicavel em processos e iniciativas especificas.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 25,
    },
    {
        "id": "P26",
        "categoria": "Preferencias",
        "pergunta": "E essencial que a opiniao dos membros da organizacao seja considerada durante as definicoes de mudanca das rotinas de analise, fornecendo feedbacks acerca de possiveis ferramentas de analise de dados e seu uso dentro da empresa.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 26,
    },
    {
        "id": "P27",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que as ferramentas e sistemas de analise sejam implementados para atender necessidades especificas do negocio, e nao apenas por razoes tecnologicas, garantindo o uso sistematico das informacoes disponiveis.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 27,
    },
    {
        "id": "P28",
        "categoria": "Preferencias",
        "pergunta": "E essencial que profissionais com ampla experiencia atuem como agentes de mudanca, disseminando praticas eficazes e removendo obstaculos no acesso e uso das informacoes.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 28,
    },
    {
        "id": "P29",
        "categoria": "Preferencias",
        "pergunta": "A organizacao deve construir um ambiente onde os colaboradores sintam-se seguros para experimentar novas abordagens, aprender com os erros e compartilhar descobertas que possam desafiar percepcoes ja existentes.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 29,
    },
    {
        "id": "P30",
        "categoria": "Preferencias",
        "pergunta": "E essencial que os colaboradores estejam abertos para compartilhar informacoes e conhecimentos entre si e que haja alinhamento e colaboracao entre os setores envolvidos.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 30,
    },
    {
        "id": "P31",
        "categoria": "Preferencias",
        "pergunta": "A empresa deve realizar sessoes praticas onde novas ferramentas sejam demonstradas e seu valor explicado, difunda relatos sobre a historia de sucesso da aplicacao, e integre esses esforcos a melhora da performance organizacional.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 31,
    },
    {
        "id": "P32",
        "categoria": "Preferencias",
        "pergunta": "E fundamental desenvolver politicas de recursos humanos que definam as competencias necessarias para analise de dados eficaz, para entao atrair talentos especializados nessas competencias e desenvolve-las nos demais membros da organizacao.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 32,
    },
    {
        "id": "P33",
        "categoria": "Preferencias",
        "pergunta": "Os lideres devem construir um ambiente onde os colaboradores sintam-se seguros para questionar, inovar e aprender com os erros, fortalecendo a confianca nas iniciativas baseadas em analise de dados.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 33,
    },
    {
        "id": "P34",
        "categoria": "Preferencias",
        "pergunta": "E essencial que os gestores evidenciem a importancia do demandem o uso de dados para decisoes, reconhecam formalmente as praticas consideradas corretas e destinem recursos para capacitacao e infraestrutura necessarias.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 34,
    },
    {
        "id": "P35",
        "categoria": "Preferencias",
        "pergunta": "E essencial reconhecer que colaboradores podem resistir em abandonar metodos familiares, que tecnologias podem ser implementadas sem explicacao adequada de seu potencial, e que existe dificuldade em admitir lacunas no proprio conhecimento.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 35,
    },
    {
        "id": "P36",
        "categoria": "Preferencias",
        "pergunta": "A empresa deve estruturar processos para sustentar a cultura, avaliando a robustez da organizacao para as praticas desejadas e orquestrando recursos e ativos para promove-las.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 36,
    },
    {
        "id": "P37",
        "categoria": "Preferencias",
        "pergunta": "A lideranca deve conhecer e comunicar os procedimentos e politicas de uso dos dados para alinhar com seus pares e subordinados acerca das regras e seus objetivos da organizacao.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 37,
    },
    {
        "id": "P38",
        "categoria": "Preferencias",
        "pergunta": "A empresa deve definir normas bem estruturadas que garantam a precisao, credibilidade e adequacao das informacoes, mantendo a integridade e a padronizacao necessarias para que os colaboradores confiem nas analises e tomem decisoes seguras.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 38,
    },
    {
        "id": "P39",
        "categoria": "Preferencias",
        "pergunta": "Os colaboradores devem estar dispostos a reformular suas bases de conhecimento quando novas informacoes contradizem praticas existentes, promovendo o refinamento de abordagens e a geracao de inovacoes em produtos e processos.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 39,
    },
    {
        "id": "P40",
        "categoria": "Preferencias",
        "pergunta": "E crucial formar equipes multidisciplinares que integrem especialistas em tecnologia e analise de dados com profissionais que possuem o conhecimento pratico das operacoes.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 40,
    },
    {
        "id": "P41",
        "categoria": "Preferencias",
        "pergunta": "A empresa deve destinar orcamento especifico para capacitacao e estruturar sistemas formais de aprendizagem, como bibliotecas de conhecimento, onde especialistas compartilhem suas experiencias e formalizem a aquisicao de novas competencias.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 41,
    },
    {
        "id": "P42",
        "categoria": "Preferencias",
        "pergunta": "E essencial que a empresa estabeleca infraestrutura robusta para coletar, armazenar e consolidar informacoes, utilizando sistemas organizados que disponibilizem os dados para as pessoas certas no momento adequado.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 42,
    },
    {
        "id": "P43",
        "categoria": "Preferencias",
        "pergunta": "E fundamental que a organizacao estabeleca regras claras sobre como administrar, compartilhar e proteger os dados de forma etica e segura, formalizando o modo como sao valorizados e utilizados nas decisoes.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 43,
    },
    {
        "id": "P44",
        "categoria": "Preferencias",
        "pergunta": "A organizacao deve desenvolver a capacidade de adquirir, assimilar e aplicar novas informacoes de forma agil, demonstrando disposicao clara para adaptar processos e comportamentos com base nos insights obtidos.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 44,
    },
    {
        "id": "P45",
        "categoria": "Preferencias",
        "pergunta": "A empresa deve medir e monitorar os resultados das iniciativas orientada a dados para aumentar a confianca nos dados e motivar os colaboradores, demonstrando os beneficios tangiveis do trabalho orientado por dados.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 45,
    },
    {
        "id": "P46",
        "categoria": "Preferencias",
        "pergunta": "A organizacao deve estabelecer um ciclo continuo de metas claras, medicao do sucesso, interacao e feedback constantes, e aprendizado a partir dos resultados, garantindo que os indicadores sejam claros e logicos para que os colaboradores gerem insights e os gerenciem de forma autonoma.",
        "tipo": "ranking",
        "opcoes": [],
        "peso": 3,
        "ordem": 46,
    },
]

SETORES = [
    {"nome": "RH"},
    {"nome": "Financeiro"},
]


async def seed() -> None:
    engine = create_async_engine(settings.database_url)
    async with engine.begin() as conn:
        for s in SETORES:
            await conn.execute(
                text("INSERT INTO public.setores (nome) VALUES (:nome) ON CONFLICT DO NOTHING"),
                {"nome": s["nome"]},
            )

        for p in PERGUNTAS_OPCOES:
            await conn.execute(
                text("""
                    INSERT INTO public.perguntas_opcoes (id, categoria, pergunta, tipo, opcoes, ordem)
                    VALUES (:id, :categoria, :pergunta, :tipo, :opcoes, :ordem)
                    ON CONFLICT (id) DO UPDATE SET
                        categoria = EXCLUDED.categoria,
                        pergunta = EXCLUDED.pergunta,
                        tipo = EXCLUDED.tipo,
                        opcoes = EXCLUDED.opcoes,
                        ordem = EXCLUDED.ordem
                """),
                {
                    "id": p["id"],
                    "categoria": p["categoria"],
                    "pergunta": p["pergunta"],
                    "tipo": p["tipo"],
                    "opcoes": json.dumps(p["opcoes"]),
                    "ordem": p["ordem"],
                },
            )

        for p in PERGUNTAS_PREFERENCIAS:
            await conn.execute(
                text("""
                    INSERT INTO public.perguntas_preferencias (id, categoria, pergunta, tipo, opcoes, peso, ordem)
                    VALUES (:id, :categoria, :pergunta, :tipo, :opcoes, :peso, :ordem)
                    ON CONFLICT (id) DO UPDATE SET
                        categoria = EXCLUDED.categoria,
                        pergunta = EXCLUDED.pergunta,
                        tipo = EXCLUDED.tipo,
                        opcoes = EXCLUDED.opcoes,
                        peso = EXCLUDED.peso,
                        ordem = EXCLUDED.ordem
                """),
                {
                    "id": p["id"],
                    "categoria": p["categoria"],
                    "pergunta": p["pergunta"],
                    "tipo": p["tipo"],
                    "opcoes": json.dumps(p["opcoes"]),
                    "peso": p["peso"],
                    "ordem": p["ordem"],
                },
            )

    await engine.dispose()
    print("Seed concluido com sucesso.")


if __name__ == "__main__":
    asyncio.run(seed())
